// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTE_jOtw6K5RSntwnZlnXi6J3ECx187hA',
    appId: '1:1058252648968:web:8c693beb4ceb4e83c717bd',
    messagingSenderId: '1058252648968',
    projectId: 'edusync-dadb5',
    authDomain: 'edusync-dadb5.firebaseapp.com',
    storageBucket: 'edusync-dadb5.firebasestorage.app',
    measurementId: 'G-9KST81KZ2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VmXqkmC1APbxcOLGoLIQAC9re47dBWY',
    appId: '1:1058252648968:android:8fd167e750fe43cfc717bd',
    messagingSenderId: '1058252648968',
    projectId: 'edusync-dadb5',
    storageBucket: 'edusync-dadb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5imjP8Bwf5rlmJZSEjO9XVW7sr7owfMM',
    appId: '1:1058252648968:ios:6527d5249b7cbe21c717bd',
    messagingSenderId: '1058252648968',
    projectId: 'edusync-dadb5',
    storageBucket: 'edusync-dadb5.firebasestorage.app',
    iosClientId: '1058252648968-t29qkphltqhc4f8470p21siadnp6t80e.apps.googleusercontent.com',
    iosBundleId: 'com.example.edusync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5imjP8Bwf5rlmJZSEjO9XVW7sr7owfMM',
    appId: '1:1058252648968:ios:6527d5249b7cbe21c717bd',
    messagingSenderId: '1058252648968',
    projectId: 'edusync-dadb5',
    storageBucket: 'edusync-dadb5.firebasestorage.app',
    iosClientId: '1058252648968-t29qkphltqhc4f8470p21siadnp6t80e.apps.googleusercontent.com',
    iosBundleId: 'com.example.edusync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTE_jOtw6K5RSntwnZlnXi6J3ECx187hA',
    appId: '1:1058252648968:web:4c003ba540932833c717bd',
    messagingSenderId: '1058252648968',
    projectId: 'edusync-dadb5',
    authDomain: 'edusync-dadb5.firebaseapp.com',
    storageBucket: 'edusync-dadb5.firebasestorage.app',
    measurementId: 'G-XW4WSR86Z6',
  );
}
